In [1]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor

In [2]:
X = np.array([
    [1, 10, 100],
    [2, 20, 200],
    [3, 30, 300]
])

y = np.array([10, 20, 30])

In [3]:
M = 2                  
learning_rate = 1.0 

In [4]:
# STEP 1:
# f0(x) = argmin_gamma Sum L(yi, gamma)
#
# For squared error:
# f0 = mean(y)

In [5]:
f = np.full(len(y), np.mean(y))

print("Initial prediction f0:")
print(f)

Initial prediction f0:
[20. 20. 20.]


In [6]:
# Gradient boosting

In [8]:
trees = []
gammas = []


for m in range(M):
    print(f"BOOSTING ITERATION {m + 1}")

BOOSTING ITERATION 1
BOOSTING ITERATION 2


In [9]:
# STEP 2(a)
    #
    # r_im = - dL/df
    #
    # For squared error:
    #
    # L = 1/2 (y - f)^2
    #
    # Negative gradient = y - f

In [12]:
residual = y - f

print("\nPseudo-residuals:")
print(residual)


Pseudo-residuals:
[-10.   0.  10.]


In [15]:
    # STEP 2(b)
    #
    # Fit regression tree to pseudo-residuals

In [16]:
tree = DecisionTreeRegressor(max_depth=1, random_state=42)
tree.fit(X, residual)
    # Tree prediction = approximate pseudo-residual
tree_prediction = tree.predict(X)
print("\nTree prediction:")
print(tree_prediction)


Tree prediction:
[-10.   5.   5.]


In [17]:
    # STEP 2(c)
    #
    # Calculate gamma for each leaf.
    #
    # For squared error:
    #
    # gamma = mean residual in the leaf

In [18]:
    leaf_ids = tree.apply(X)

    unique_leaves = np.unique(leaf_ids)

    gamma_dict = {}

    print("\nLeaf calculations:")

    for leaf in unique_leaves:

        indices = np.where(leaf_ids == leaf)[0]

        leaf_residuals = residual[indices]

        gamma = np.mean(leaf_residuals)

        gamma_dict[leaf] = gamma

        print(f"Leaf {leaf}")
        print("Rows:", indices)
        print("Residuals:", leaf_residuals)
        print("Gamma:", gamma)


Leaf calculations:
Leaf 1
Rows: [0]
Residuals: [-10.]
Gamma: -10.0
Leaf 2
Rows: [1 2]
Residuals: [ 0. 10.]
Gamma: 5.0


In [19]:
  # STEP 2(d)
    #
    # f_m(x)
    #
    # = f_(m-1)(x)
    # + learning_rate * gamma

In [20]:
    correction = np.array([
        gamma_dict[leaf]
        for leaf in leaf_ids
    ])

    f = f + learning_rate * correction

    print("\nCorrection:")
    print(correction)

    print("\nUpdated prediction:")
    print(f)


    trees.append(tree)
    gammas.append(gamma_dict)


Correction:
[-10.   5.   5.]

Updated prediction:
[10. 25. 25.]


In [21]:
print("FINAL PREDICTIONS")
print(f)

FINAL PREDICTIONS
[10. 25. 25.]
